export {default as Home} from './Home'
export {default as Tv} from './Tv'
export {default as Navbar} from './Navbar'
export {default as SideBar} from './SideBar'
export {default as MovieSection} from './MovieSection'
export {default as MovieDetail} from './MovieDetail'
export {default as MoviePage} from './MoviePage'
export {default as TvPage} from './TvPage'